server.port=${PORT:8080}

server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
server.forward-headers-strategy=framework

frontend.url=${PRODUCTION_FRONTEND_URL}
backend.url=${PRODUCTION_BACKEND_URL}

# SSL connection
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=
#server.ssl.key-alias=springboot