server.port=${PORT:8080}
frontend.url=${PRODUCTION_FRONTEND_URL}
backend.url=${PRODUCTION_BACKEND_URL}

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=true
server.forward-headers-strategy=framework